const endpoint = process.argv[2] || 'http://127.0.0.1:9222'
const siteUrl = process.argv[3] || 'http://127.0.0.1:5173'
const targets = await fetch(`${endpoint}/json`).then(response => response.json())
const target = targets.find(item => item.type === 'page' && item.url.startsWith(siteUrl))
if (!target) throw new Error('TL2 Wiki page target not found')

const socket = new WebSocket(target.webSocketDebuggerUrl)
await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject })
let id = 0
const pending = new Map()
socket.onmessage = event => {
  const message = JSON.parse(event.data)
  if (message.id && pending.has(message.id)) { pending.get(message.id)(message); pending.delete(message.id) }
}
const call = (method, params = {}) => new Promise(resolve => {
  const requestId = ++id
  pending.set(requestId, resolve)
  socket.send(JSON.stringify({ id: requestId, method, params }))
})
const evaluate = async expression => (await call('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true })).result.result.value
const wait = ms => new Promise(resolve => setTimeout(resolve, ms))

await evaluate(`location.hash='#/home'; location.reload()`)
await wait(500)
const loaded = await evaluate(`document.body.textContent.includes('3,840')`)
if (!loaded) throw new Error('Equipment count was not rendered')
const before = await evaluate(`Boolean(document.querySelector('.search-modal'))`)
if (before) throw new Error('Search modal unexpectedly open before keyboard test')
await evaluate(`window.dispatchEvent(new KeyboardEvent('keydown',{key:'k',code:'KeyK',ctrlKey:true,bubbles:true}))`)
await wait(100)
const after = await evaluate(`Boolean(document.querySelector('.search-modal')) && document.activeElement?.tagName === 'INPUT'`)
if (!after) throw new Error('Ctrl+K did not open and focus global search')
await evaluate(`window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',code:'Escape',bubbles:true}))`)
await wait(100)
const closed = await evaluate(`!document.querySelector('.search-modal')`)
if (!closed) throw new Error('Escape did not close global search')
await evaluate(`(() => { const select=document.querySelector('.locale-select select'); select.value='zh-TW'; select.dispatchEvent(new Event('change',{bubbles:true})); })()`)
await wait(100)
const language = await evaluate(`document.documentElement.lang`)
if (language !== 'zh-TW') throw new Error(`Traditional Chinese selection did not update document language: ${language}`)

await evaluate(`location.hash='#/classes'`)
await wait(250)
const skillData = await evaluate(`Boolean(document.querySelector('.skill-table img')?.complete && document.querySelector('.rank-control input')?.max==='15' && document.querySelector('.skill-metrics'))`)
if (!skillData) throw new Error('Skill icons or rank values were not rendered')

await evaluate(`location.hash='#/items'`)
await wait(250)
const setSearch = value => evaluate(`(() => {
  const input=document.querySelector('.data-search input');
  const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;
  setter.call(input,${JSON.stringify(value)});
  input.dispatchEvent(new Event('input',{bubbles:true}));
})()`)
await setSearch('All Damage Taken is reduced by 3%')
await wait(150)
const effectSearchWorked = await evaluate(`document.querySelectorAll('.data-table tbody tr').length > 0`)
if (!effectSearchWorked) throw new Error('Equipment effect text was not searchable')
const equipmentColumns = await evaluate(`document.querySelectorAll('.data-table thead th').length`)
if (equipmentColumns !== 6) throw new Error('Equipment table still exposes the removed socket column')
await setSearch('The Eye of Grell')
await wait(150)
await evaluate(`document.querySelector('.data-table tbody tr')?.click()`)
await wait(100)
const effectDetail = await evaluate(`document.querySelector('.raw-effect-list')?.textContent.includes('爆擊率') && !document.querySelector('.detail-grid')?.textContent.includes('孔數')`)
if (!effectDetail) throw new Error('Localized raw equipment effects were not shown or sockets remain in the detail drawer')
await evaluate(`document.querySelector('.drawer-close')?.click()`)
await setSearch("Arcgap's Vice")
await wait(150)
await evaluate(`document.querySelector('.data-table tbody tr')?.click()`)
await wait(100)
const weaponInterval = await evaluate(`document.querySelector('.detail-grid')?.textContent.includes('基礎攻擊間隔')`)
if (!weaponInterval) throw new Error('Weapon base attack interval was not rendered')
await evaluate(`document.querySelector('.drawer-close')?.click()`)
await setSearch('Ascendant Armor')
await wait(150)
const independentSetTag = await evaluate(`(() => {
  const row=document.querySelector('.data-table tbody tr');
  return Boolean(row?.querySelector('.rarity.unique') && row?.querySelector('.set-tag') && row?.querySelector('.rarity-border.unique'))
})()`)
if (!independentSetTag) throw new Error('Set membership replaced rarity or the icon rarity border is missing')
const styledSelects = await evaluate(`(() => {
  const controls=[...document.querySelectorAll('.data-toolbar .select-control')];
  const rarity=controls[1]?.querySelector('select');
  return controls.length===3 && getComputedStyle(rarity).appearance==='none' && ![...rarity.options].some(option=>option.value==='set')
})()`)
if (!styledSelects) throw new Error('Equipment filters are not using the shared styled select control')
await evaluate(`location.hash='#/mechanics'`)
await wait(200)
const socketRules = await evaluate(`document.querySelectorAll('.socket-rules article').length===4 && document.body.textContent.includes('Netherrealm')`)
if (!socketRules) throw new Error('Socket mechanics were not rendered')

await evaluate(`location.hash='#/builds'`)
await wait(250)
const buildShell = await evaluate(`document.querySelectorAll('.gear-slot').length===12 && document.body.textContent.includes('495')`)
if (!buildShell) throw new Error('Build planner slots or point budget were not rendered')
await evaluate(`document.querySelectorAll('.gear-slot')[5]?.click()`)
await wait(100)
await evaluate(`(() => { const input=document.querySelector('.picker-search input'); const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set; setter.call(input,"Arcgap's Vice"); input.dispatchEvent(new Event('input',{bubbles:true})); })()`)
await wait(120)
await evaluate(`document.querySelectorAll('.picker-list > button')[1]?.click()`)
await wait(120)
const buildSelection = await evaluate(`document.querySelectorAll('.gear-slot.filled').length===1 && !document.querySelector('.derived-grid')?.textContent.includes('武器基礎傷害—')`)
if (!buildSelection) throw new Error('Build planner did not equip and inspect a weapon')

await evaluate(`location.hash='#/gambling'`)
await wait(200)
await evaluate(`(() => { const select=document.querySelector('.gamble-controls select'); select.value='helmet'; select.dispatchEvent(new Event('change',{bubbles:true})); const inputs=document.querySelectorAll('.gamble-controls input'); const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set; setter.call(inputs[0],'50'); inputs[0].dispatchEvent(new Event('input',{bubbles:true})); setter.call(inputs[1],'1'); inputs[1].dispatchEvent(new Event('input',{bubbles:true})); })()`)
await wait(120)
const gamblePrices = await evaluate(`(() => { const values=[...document.querySelectorAll('.price-row b')].map(node=>node.textContent); return values.length===8 && values[0]==='4,336' && values[1]==='4,337' })()`)
if (!gamblePrices) throw new Error('Gambling calculator did not render the expected eight rounded prices')
await evaluate(`location.hash='#/spells'`)
await wait(200)
const localizedSpells = await evaluate(`document.body.textContent.includes('興奮爆發') && document.body.textContent.includes('這本秘笈')`)
if (!localizedSpells) throw new Error('Complete database-provided spell-book locales were not rendered')
await evaluate(`location.hash='#/phases'`)
await wait(250)
const phasePage = await evaluate(`(() => { const image=document.querySelector('.phase-guide img'); return Boolean(image?.complete && image.naturalWidth>0 && document.querySelectorAll('.phase-card').length===6 && document.querySelectorAll('.challenge-list section').length===15 && document.body.textContent.includes('接近圖騰')) })()`)
if (!phasePage) throw new Error('Phase Beast guide, areas or challenges did not render')
await call('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
await wait(100)
const mobileFits = await evaluate(`document.documentElement.scrollWidth <= 390`)
if (!mobileFits) throw new Error('Mobile layout has horizontal overflow')
await evaluate(`location.hash='#/builds'`)
await wait(150)
const mobileBuildFits = await evaluate(`document.documentElement.scrollWidth <= 390 && document.querySelectorAll('.gear-slot').length===12`)
if (!mobileBuildFits) throw new Error('Mobile build planner overflows or lost equipment slots')
await evaluate(`location.hash='#/gambling'`)
await wait(150)
const mobileGamblingFits = await evaluate(`document.documentElement.scrollWidth <= 390 && document.querySelectorAll('.price-row b').length===8`)
if (!mobileGamblingFits) throw new Error('Mobile gambling calculator overflows or lost price outcomes')
await call('Emulation.clearDeviceMetricsOverride')

socket.close()
console.log('Browser smoke test passed: data, shortcuts, languages, localized equipment effects, socket rules, build planner, gambling calculator, Phase Beast guide and mobile fit')
