const endpoint = process.argv[2] || 'http://127.0.0.1:9222'
const siteUrl = process.argv[3] || 'http://127.0.0.1:5173'
const targets = await fetch(`${endpoint}/json`).then(response => response.json())
const target = targets.find(item => item.type === 'page' && item.url.startsWith(siteUrl))
if (!target) throw new Error('TL2 Wiki page target not found')

const socket = new WebSocket(target.webSocketDebuggerUrl)
await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject })
let id = 0
const pending = new Map()
socket.onmessage = event => {
  const message = JSON.parse(event.data)
  if (message.id && pending.has(message.id)) { pending.get(message.id)(message); pending.delete(message.id) }
}
const call = (method, params = {}) => new Promise(resolve => {
  const requestId = ++id
  pending.set(requestId, resolve)
  socket.send(JSON.stringify({ id: requestId, method, params }))
})
const evaluate = async expression => (await call('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true })).result.result.value
const wait = ms => new Promise(resolve => setTimeout(resolve, ms))
await call('Emulation.clearDeviceMetricsOverride')
const chooseOption = async (selector, value) => {
  await evaluate(`document.querySelector(${JSON.stringify(selector)})?.querySelector('.select-trigger')?.click()`)
  await wait(60)
  await evaluate(`(() => { const root=document.querySelector(${JSON.stringify(selector)}); [...(root?.querySelectorAll('.select-option')||[])].find(option=>option.dataset.value===${JSON.stringify(value)})?.click(); })()`)
  await wait(80)
}

await evaluate(`location.hash='#/home'; location.reload()`)
await wait(500)
const loaded = await evaluate(`document.body.textContent.includes('3,840')`)
if (!loaded) throw new Error('Equipment count was not rendered')
const homeCards = await evaluate(`(() => {
  const cards=[...document.querySelectorAll('.quick-grid > button')];
  const pill=document.querySelector('.attribute-list .stat-pill');
  return cards.length===4 && cards.every(card=>card.querySelector(':scope > .quick-meta > svg') && !card.querySelector(':scope > svg'))
    && getComputedStyle(pill).height==='28px' && getComputedStyle(pill).width==='52px';
})()`)
if (!homeCards) throw new Error('Home card arrows or attribute pills are misaligned')
const before = await evaluate(`Boolean(document.querySelector('.search-modal'))`)
if (before) throw new Error('Search modal unexpectedly open before keyboard test')
await evaluate(`window.dispatchEvent(new KeyboardEvent('keydown',{key:'k',code:'KeyK',ctrlKey:true,bubbles:true}))`)
await wait(100)
const after = await evaluate(`Boolean(document.querySelector('.search-modal')) && document.activeElement?.tagName === 'INPUT'`)
if (!after) throw new Error('Ctrl+K did not open and focus global search')
await evaluate(`window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',code:'Escape',bubbles:true}))`)
await wait(100)
const closed = await evaluate(`!document.querySelector('.search-modal')`)
if (!closed) throw new Error('Escape did not close global search')
await chooseOption('.locale-select','zh-TW')
const language = await evaluate(`document.documentElement.lang`)
if (language !== 'zh-TW') throw new Error(`Traditional Chinese selection did not update document language: ${language}`)

await evaluate(`location.hash='#/classes'`)
await wait(250)
const skillData = await evaluate(`Boolean(document.querySelector('.skill-table img')?.complete && document.querySelector('.rank-control input')?.max==='15' && document.querySelector('.skill-metrics'))`)
if (!skillData) throw new Error('Skill icons or rank values were not rendered')

await evaluate(`location.hash='#/items'`)
await wait(250)
const setSearch = value => evaluate(`(() => {
  const input=document.querySelector('.data-search input');
  const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;
  setter.call(input,${JSON.stringify(value)});
  input.dispatchEvent(new Event('input',{bubbles:true}));
})()`)
await setSearch('All Damage Taken is reduced by 3%')
await wait(150)
const effectSearchWorked = await evaluate(`document.querySelectorAll('.data-table tbody tr').length > 0`)
if (!effectSearchWorked) throw new Error('Equipment effect text was not searchable')
const equipmentColumns = await evaluate(`document.querySelectorAll('.data-table thead th').length`)
if (equipmentColumns !== 6) throw new Error('Equipment table still exposes the removed socket column')
await setSearch('The Eye of Grell')
await wait(150)
await evaluate(`document.querySelector('.data-table tbody tr')?.click()`)
await wait(100)
const effectDetail = await evaluate(`document.querySelector('.raw-effect-list')?.textContent.includes('爆擊率') && !document.querySelector('.detail-grid')?.textContent.includes('孔數')`)
if (!effectDetail) throw new Error('Localized raw equipment effects were not shown or sockets remain in the detail drawer')
await evaluate(`document.querySelector('.drawer-close')?.click()`)
await setSearch("Arcgap's Vice")
await wait(150)
await evaluate(`document.querySelector('.data-table tbody tr')?.click()`)
await wait(100)
const weaponSpeed = await evaluate(`document.querySelector('.item-base-values')?.textContent.includes('1,009 每秒傷害') && document.querySelector('.item-base-values')?.textContent.includes('0.8s 攻擊間隔')`)
if (!weaponSpeed) throw new Error('Weapon DPS or attack interval was not rendered')
await evaluate(`document.querySelector('.drawer-close')?.click()`)
await setSearch('Ascendant Armor')
await wait(150)
const independentSetTag = await evaluate(`(() => {
  const row=document.querySelector('.data-table tbody tr');
  return Boolean(row?.textContent.includes('優越護衣') && row?.querySelector('.rarity.unique') && row?.querySelector('.set-tag') && row?.querySelector('.rarity-border.unique'))
})()`)
if (!independentSetTag) throw new Error('Set membership replaced rarity or the icon rarity border is missing')
await evaluate(`document.querySelector('.data-table tbody tr')?.click()`)
await wait(100)
const localizedClassRequirement = await evaluate(`document.querySelector('.detail-section')?.parentElement?.textContent.includes('職業：燼法師') && !document.querySelector('.detail-section')?.parentElement?.textContent.includes('職業：Embermage')`)
if (!localizedClassRequirement) throw new Error('Equipment class requirement was not localized')
await evaluate(`document.querySelector('.drawer-close')?.click()`)
await evaluate(`document.querySelector('.data-toolbar .select-control .select-trigger')?.click()`)
await wait(80)
const styledSelects = await evaluate(`(() => {
  const controls=[...document.querySelectorAll('.data-toolbar .select-control')];
  const menu=controls[0]?.querySelector('.select-menu');
  const options=[...(menu?.querySelectorAll('.select-option')||[])];
  return controls.length===3 && menu?.getAttribute('role')==='listbox' && options.length===6
    && getComputedStyle(menu).borderRadius==='10px' && getComputedStyle(menu).boxShadow!=='none'
    && menu.textContent.includes('武器') && menu.textContent.includes('護甲') && !options.some(option=>option.dataset.value==='set')
})()`)
if (!styledSelects) throw new Error('Equipment filters are not using the shared styled select control')
await evaluate(`document.querySelector('.data-toolbar .select-control .select-trigger')?.click()`)
await evaluate(`document.querySelectorAll('.data-toolbar .select-trigger')[1]?.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}))`)
await wait(60)
await evaluate(`document.querySelectorAll('.data-toolbar .select-trigger')[1]?.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));document.querySelectorAll('.data-toolbar .select-trigger')[1]?.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))`)
await wait(100)
const keyboardSelect = await evaluate(`document.querySelectorAll('.data-toolbar .select-trigger')[1]?.textContent.includes('稀有') && document.querySelectorAll('.data-toolbar .select-trigger')[1]?.getAttribute('aria-expanded')==='false'`)
if (!keyboardSelect) throw new Error('Custom select keyboard navigation did not choose and close an option')
await chooseOption('.data-toolbar .select-control:nth-of-type(2)','all')
await evaluate(`location.hash='#/mechanics'`)
await wait(200)
const socketRules = await evaluate(`(() => { const paragraphs=document.querySelectorAll('.socket-rule-copy'); const text=paragraphs[0]?.textContent||''; return paragraphs.length===1 && paragraphs[0].querySelectorAll(':scope > span').length===3 && text.includes('0–2') && text.includes('打孔匠朱瑞克') && text.includes('「窒息」') && text.includes('「奧拉克之手」') && text.includes('牧牛人領地盾') && text.indexOf('一般初始孔數')<text.indexOf('打孔上限') && text.indexOf('打孔上限')<text.indexOf('特殊裝備'); })()`)
if (!socketRules) throw new Error('Socket mechanics were not rendered')
const focusMechanics = await evaluate(`(() => { const card=document.querySelector('.stat-summary.foc'); const tips=card?.querySelectorAll('.inline-tooltip [role="tooltip"]'); return Boolean(card?.textContent.includes('0.5 點法力上限') && card?.textContent.includes('0.5% 的任何固定傷害') && tips?.[0]?.textContent.includes('投擲迴旋鏢') && tips?.[0]?.textContent.includes('DoT') && tips?.[1]?.textContent.includes('DPS%')); })()`)
if (!focusMechanics) throw new Error('Focus fixed-damage copy or tooltip was not rendered')
await chooseOption('.locale-select','en')
const englishSocketCopy = await evaluate(`document.querySelector('.socket-rule-copy')?.textContent.includes('Initial sockets.') && document.body.textContent.includes('Socketing cap.') && document.body.textContent.includes('Special items.') && document.body.textContent.includes('Jurick the Socketer')`)
if (!englishSocketCopy) throw new Error('English socket-rule copy was not localized')
await chooseOption('.locale-select','zh-CN')
const simplifiedSocketCopy = await evaluate(`document.querySelector('.socket-rule-copy')?.textContent.includes('一般初始孔数：') && document.body.textContent.includes('特殊装备：') && document.body.textContent.includes('打孔师朱瑞克') && document.body.textContent.includes('“奥拉克之手”') && document.body.textContent.includes('冥界盾牌')`)
if (!simplifiedSocketCopy) throw new Error('Simplified Chinese socket-rule copy was not localized')
await chooseOption('.locale-select','zh-TW')

await evaluate(`location.hash='#/builds'`)
await wait(250)
await evaluate(`document.querySelector('.build-toolbar .planner-select .select-trigger')?.click()`)
await wait(80)
const localizedClassOptions = await evaluate(`(() => { const text=document.querySelector('.build-toolbar .planner-select .select-menu')?.textContent||''; return ['狂戰士','異域行者','燼法師','工程師'].every(name=>text.includes(name))&&!text.includes('Berserker'); })()`)
if (!localizedClassOptions) throw new Error('Build-planner class options were not localized')
await evaluate(`document.querySelector('.build-toolbar .planner-select .select-trigger')?.click()`)
await evaluate(`document.querySelector('.reset-build')?.click()`)
const buildShell = await evaluate(`document.querySelectorAll('.gear-slot').length===12 && document.body.textContent.includes('495')`)
if (!buildShell) throw new Error('Build planner slots or point budget were not rendered')
await evaluate(`document.querySelectorAll('.gear-slot')[0]?.querySelector('.slot-empty')?.click()`)
await wait(100)
await evaluate(`(() => { const input=document.querySelector('.picker-search input'); const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set; setter.call(input,"Axe of the Elder One"); input.dispatchEvent(new Event('input',{bubbles:true})); })()`)
await wait(120)
await evaluate(`document.querySelectorAll('.picker-list > button')[1]?.click()`)
await wait(120)
await evaluate(`document.querySelector('.gear-preview .preview-replace')?.click()`)
await wait(120)
const buildSelection = await evaluate(`document.querySelectorAll('.gear-slot.filled').length===1 && !document.querySelector('.gear-preview') && !document.querySelector('.derived-grid')?.textContent.includes('武器基礎傷害—') && document.querySelector('.derived-grid')?.textContent.includes('專注傷害加成')`)
if (!buildSelection) throw new Error('Build planner did not equip and inspect a weapon')
await evaluate(`document.querySelector('.gear-slot.filled .slot-preview')?.click()`)
await wait(100)
const buildQuickView = await evaluate(`(() => { const preview=document.querySelector('.gear-preview'); const values=preview?.querySelector('.gear-preview-values'); return Boolean(preview?.textContent.includes('酸雨') && preview.querySelector('.preview-replace') && ![...(values?.childNodes||[])].some(node=>node.nodeType===Node.TEXT_NODE&&node.textContent.trim())); })()`)
if (!buildQuickView) throw new Error('Build planner equipment quick view did not show localized effects')
await evaluate(`document.querySelector('.gear-preview > header button')?.click()`)
await chooseOption('.build-toolbar .planner-select','outlander')
await wait(120)
await evaluate(`document.querySelectorAll('.gear-slot')[10]?.querySelector('.slot-empty')?.click()`)
await wait(100)
await evaluate(`(() => { const input=document.querySelector('.picker-search input'); const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set; setter.call(input,"Ring of the Players"); input.dispatchEvent(new Event('input',{bubbles:true})); })()`)
await wait(120)
await evaluate(`document.querySelectorAll('.picker-list > button')[1]?.click()`)
await wait(120)
await evaluate(`document.querySelector('.gear-preview .preview-replace')?.click()`)
await wait(120)
const roundedPlannerStats = await evaluate(`(() => { const dex=document.querySelector('.stat-allocation.dex'); return Boolean(dex?.querySelector('small')?.textContent.includes('15 + 20') && dex?.querySelector(':scope > strong')?.textContent.trim()==='35' && !document.body.textContent.includes('19.464')); })()`)
if (!roundedPlannerStats) throw new Error('Build planner did not use the final rounded equipment attribute value')

await evaluate(`location.hash='#/gambling'`)
await wait(200)
await chooseOption('.gamble-controls .select-control','helmet')
await evaluate(`(() => { const inputs=document.querySelectorAll('.gamble-controls input'); const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set; setter.call(inputs[0],'50'); inputs[0].dispatchEvent(new Event('input',{bubbles:true})); setter.call(inputs[1],'1'); inputs[1].dispatchEvent(new Event('input',{bubbles:true})); })()`)
await wait(120)
const gamblePrices = await evaluate(`(() => { const values=[...document.querySelectorAll('.price-row b')].map(node=>node.textContent); return values.length===8 && values[0]==='4,336' && values[1]==='4,337' })()`)
if (!gamblePrices) throw new Error('Gambling calculator did not render the expected eight rounded prices')
const gamblingCopy = await evaluate(`document.body.textContent.includes('價格計算方式') && document.body.textContent.includes('無條件捨去')`)
if (!gamblingCopy) throw new Error('Traditional Chinese gambling copy was not revised')
await evaluate(`location.hash='#/spells'`)
await wait(200)
const localizedSpells = await evaluate(`document.body.textContent.includes('興奮爆發') && document.body.textContent.includes('這本秘笈')`)
if (!localizedSpells) throw new Error('Complete database-provided spell-book locales were not rendered')
await evaluate(`location.hash='#/phases'`)
await wait(250)
const phasePage = await evaluate(`(() => { const image=document.querySelector('.phase-guide img'); return Boolean(image?.complete && image.naturalWidth>0 && document.querySelectorAll('.phase-card').length===6 && document.querySelectorAll('.challenge-list section').length===15 && document.body.textContent.includes('接近圖騰')) })()`)
if (!phasePage) throw new Error('Phase Beast guide, areas or challenges did not render')
await call('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
await wait(100)
const mobileFits = await evaluate(`document.documentElement.scrollWidth <= 390`)
if (!mobileFits) throw new Error('Mobile layout has horizontal overflow')
await evaluate(`location.hash='#/mechanics'`)
await wait(150)
const mobileMechanicsFits = await evaluate(`document.documentElement.scrollWidth <= 390 && document.querySelectorAll('.socket-rule-copy').length===1`)
if (!mobileMechanicsFits) throw new Error('Mobile socket mechanics overflow or lost their single-paragraph structure')
await evaluate(`location.hash='#/builds'`)
await wait(150)
const mobileBuildFits = await evaluate(`document.documentElement.scrollWidth <= 390 && document.querySelectorAll('.gear-slot').length===12`)
if (!mobileBuildFits) throw new Error('Mobile build planner overflows or lost equipment slots')
await evaluate(`location.hash='#/gambling'`)
await wait(150)
const mobileGamblingFits = await evaluate(`document.documentElement.scrollWidth <= 390 && document.querySelectorAll('.price-row b').length===8`)
if (!mobileGamblingFits) throw new Error('Mobile gambling calculator overflows or lost price outcomes')
await call('Emulation.clearDeviceMetricsOverride')

socket.close()
console.log('Browser smoke test passed: data, shortcuts, languages, localized equipment effects, socket rules, build planner, gambling calculator, Phase Beast guide and mobile fit')
